### ISSUE TITLE
Plan: 有没有可能建立一个必修课程指引呢

### ISSUE THREAD

**Issue by StuGRua** [NAOSI-DLUT/DLUT_SE_Courses#22]
有没有可能建立一个必修课程指引呢
- 前置：通过问卷调查来对课程复习难度进行分级
- 详细构建：给出学习建议，标注重难点，对相关资源做出索引，整合到md中

**Comment by dingiso** [comment]
你的想法很好，这是在资源完善的情况下对于仓库的下一部分提升，但是现在由于几点限制并不能很好的做到
* 我们需要尽量保持客观和中立，所以我们希望可以以个人的形式把自己对课程的重难点和难度写在自己的笔记中，我们只负责展示并不主观评判，当人数较多时可以来做下一步整合
* 每个人所认为的重难点其实并不重要（bushi，详情见下句），老师认为才重要，不是么（🤭）?
* 其实我在review时对资源做出了过滤，资源也以合理的方式组织了，**索引**暂时觉得资源少的情况下还不太优先。
非常感谢你的意见，我会从中提取观点，先对同学们的选修课程避坑做出 问卷调查写出指南，必修 的 难度审查也可以先开始进行

**Comment by dingiso** [comment]
已建立，ok
