### ISSUE TITLE
建议添加课程评价

### ISSUE THREAD

**Issue by beautifulwq** [NAOSI-DLUT/DLUT_SE_Courses#61]
建议添加课程评价，如

- 课程考核方式（大作业/考试）
- 是否查签到
- 课程教学质量（是否能用网课替补/自学）
- others

**Comment by Augists** [comment]
课程评价在仓库右边description部分里的网站里，但是长时间没有访问和维护
如果你有兴趣，可以联系NAOSI工作人员
