### ISSUE TITLE
建议重新整理资料目录，把所有专业选修课（非必修通识课程）单独放到一个文件夹里，其余选修（美育四史等）放到另一文件夹

### ISSUE THREAD

**Issue by Lentinel** [NAOSI-DLUT/DLUT_SE_Courses#86]

**Comment by Augists** [comment]
我感觉可能最好是能用submodule拆分，软件软国都可以添加通识课的submodule

**Comment by Augists** [comment]
(弱弱问 愿意整理资料目录嘛

**Comment by Lentinel** [comment]
> (弱弱问 愿意整理资料目录嘛



> 我感觉可能最好是能用submodule拆分，软件软国都可以添加通识课的submodule

软件和软国的公共课程并不太一样，感觉submodule不大行。资料我有时间试着整理一下

**Comment by Lentinel** [comment]
> (弱弱问 愿意整理资料目录嘛

资料体积太大，每次push到一半就The remote disconnected. Check your Internet connection and try again.   懒得搞了= =

**Comment by Augists** [comment]
> > (弱弱问 愿意整理资料目录嘛
> 
> 资料体积太大，每次push到一半就The remote disconnected. Check your Internet connection and try again. 懒得搞了= =

好吧，所以才想用 submodule 拆分开 :cry: 以及两个学院合并了，感觉仓库也需要合并一下？问问意见

**Comment by Lentinel** [comment]
> > > (弱弱问 愿意整理资料目录嘛
> > 
> > 
> > 资料体积太大，每次push到一半就The remote disconnected. Check your Internet connection and try again. 懒得搞了= =
> 
> 好吧，所以才想用 submodule 拆分开 😢 以及两个学院合并了，感觉仓库也需要合并一下？问问意见

学院合并了课程也不一样，软国和软件的资料没啥必要合并倒是
